<?php

return [
    'apex' => [
        'characters' => [
            'Wraith',
            'Gibraltar',
            'Bloodhound',
            'Wattson',
            'Loba',
            'Horizon',
            'Pathfinder',
            'Mirage',
            'Octane',
            'Bangalore',
            'Lifeline',
            'Rampart',
            'Valkyrie',
            'Fuse',
            'Caustic',
            'Revenant',
            'Crypto',
            'Seer',
            'Ash',
            'Newcastle',
            'Mad maggie',
            'Catalyst',
        ],
        'ranks' => [
            'Rookie 1',
            'Rookie 2',
            'Rookie 3',
            'Rookie 4',
            'Bronze 1',
            'Bronze 2',
            'Bronze 3',
            'Bronze 4',
            'Silver 1',
            'Silver 2',
            'Silver 3',
            'Silver 4',
            'Gold 1',
            'Gold 2',
            'Gold 3',
            'Gold 4',
            'Platinum 1',
            'Platinum 2',
            'Platinum 3',
            'Platinum 4',
            'Diamond 1',
            'Diamond 2',
            'Diamond 3',
            'Diamond 4',
            'Apex predator',
        ],
    ],
    'lol' => [
        'positions' => [
            'Top',
            'Jungle',
            'Middle',
            'Bottom',
            'Utility',
        ],

        'positionMapping' => [
            'Utility' => 'Support',
            'Middle' => 'Mid',
            'Bottom' => 'Bot',
        ],

        'ranks' => [
            'Iron I',
            'Iron II',
            'Iron III',
            'Iron IV',
            'Bronze I',
            'Bronze II',
            'Bronze III',
            'Bronze IV',
            'Silver I',
            'Silver II',
            'Silver III',
            'Silver IV',
            'Gold I',
            'Gold II',
            'Gold III',
            'Gold IV',
            'Platinum I',
            'Platinum II',
            'Platinum III',
            'Platinum IV',
            'Diamond I',
            'Diamond II',
            'Diamond III',
            'Diamond IV',
            'Master',
            'Grandmaster',
            'Challenger',
        ],

        'regionRouting' => [
            'br1' => [
                'plattformBaseUrl' => 'https://br1.api.riotgames.com',
                'regionBaseUrl' => 'https://americas.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/br.json',
            ],
            'eun1' => [
                'plattformBaseUrl' => 'https://eun1.api.riotgames.com',
                'regionBaseUrl' => 'https://europe.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/eune.json',
            ],
            'euw1' => [
                'plattformBaseUrl' => 'https://euw1.api.riotgames.com',
                'regionBaseUrl' => 'https://europe.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/euw.json',
            ],
            'jp1' => [
                'plattformBaseUrl' => 'https://jp1.api.riotgames.com',
                'regionBaseUrl' => 'https://asia.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/jp.json',
            ],
            'kr' => [
                'plattformBaseUrl' => 'https://kr.api.riotgames.com',
                'regionBaseUrl' => 'https://asia.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/kr.json',
            ],
            'la1' => [
                'plattformBaseUrl' => 'https://la1.api.riotgames.com',
                'regionBaseUrl' => 'https://americas.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/las.json',
            ],
            'la2' => [
                'plattformBaseUrl' => 'https://la2.api.riotgames.com',
                'regionBaseUrl' => 'https://americas.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/las.json',
            ],
            'na1' => [
                'plattformBaseUrl' => 'https://na1.api.riotgames.com',
                'regionBaseUrl' => 'https://americas.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/na.json',
            ],
            'oc1' => [
                'plattformBaseUrl' => 'https://oc1.api.riotgames.com',
                'regionBaseUrl' => 'https://sea.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/oce.json',
            ],
            'tr1' => [
                'plattformBaseUrl' => 'https://tr1.api.riotgames.com',
                'regionBaseUrl' => 'https://europe.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/tr.json',
            ],
            'ru' => [
                'plattformBaseUrl' => 'https://ru.api.riotgames.com',
                'regionBaseUrl' => 'https://europe.api.riotgames.com',
                'realmUrl' => 'https://ddragon.leagueoflegends.com/realms/ru.json',
            ],
        ],
    ],
];
