name: Publish to Dockerhub

on:
  release:
    types: [ published ]
  push:
    branches:
      - development

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
          php_extensions: mysqli pdo pdo_mysql posix zip
          args: --ignore-platform-reqs

      - uses: php-actions/phpstan@v3
        with:
          php_version: 8.1
          php_extensions: mysqli pdo pdo_mysql posix zip
          configuration: phpstan.neon
          memory_limit: 1G

      - name: Laravel Pint code style analysis
        run: composer sniff

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: domenikus/game-bot

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args:
            version=${{steps.get_version.outputs.version}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
